# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music_embeddings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16music_embeddings.proto\"\x1f\n\nEmbeddings\x12\x11\n\tembedding\x18\x01 \x03(\x02\"f\n\x0fMusicEmbeddings\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\x1f\n\nembeddings\x18\x02 \x03(\x0b\x32\x0b.Embeddings\x12\x0f\n\x07\x61rtists\x18\x03 \x03(\t\x12\x0e\n\x06tracks\x18\x04 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_embeddings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDINGS._serialized_start=26
  _EMBEDDINGS._serialized_end=57
  _MUSICEMBEDDINGS._serialized_start=59
  _MUSICEMBEDDINGS._serialized_end=161
# @@protoc_insertion_point(module_scope)